### ISSUE TITLE
/areachairs tool should show emails too

### ISSUE THREAD

**Issue by OriolVinyals** [iesl/OpenReviewPy#24]
Area Chairs may need to chase down reviewers individually. Unless there is another way to do so, the tool exposed through the web summary should also show emails or a way to contact the reviewers directly.

**Comment by mspector** [comment]
What is the timeline for this? (when do you expect that the area chairs will need this?) I ask because it turns out that the public profiles that we would use to get the email addresses only reveal users' partial addresses, for security reasons. 

If they need this information very soon, I can generate a list of IDs-->emails

**Comment by OriolVinyals** [comment]
Probably Dec 2 since it's when some reviewers may need to be chased (that's the first deadline for reviewing).

**Comment by mspector** [comment]
sounds good, thanks!

**Comment by OriolVinyals** [comment]
Let me know when this is done so I can ask the AC who requested it to test it : )

**Comment by mspector** [comment]
done - you can go ahead and have your AC test it out.
